objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adresse_Ville__c</fullName>
        <label>Adresse courante: Ville</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeAPE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NAF</label>
        <referenceTo>NAF__c</referenceTo>
        <relationshipLabel>Comptes</relationshipLabel>
        <relationshipName>Comptes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CodePays__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adresse courante: Pays</label>
        <referenceTo>Pays__c</referenceTo>
        <relationshipLabel>Comptes</relationshipLabel>
        <relationshipName>Comptes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIRET__c</fullName>
        <label>SIRET</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Adresse_Ville__c</fullName>
        <label>Adresse: Ville</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Modification_Fiche__c</fullName>
        <label>Date Modification Fiche</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Famille_Fonction__c</fullName>
        <label>Famille Fonction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Autres</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Commercial/Ventes</fullName>
                </value>
                <value>
                    <fullName>Direction Générale</fullName>
                </value>
                <value>
                    <fullName>Enseignement/Education</fullName>
                </value>
                <value>
                    <fullName>Etud/Recherche/Dévelop/Qualité</fullName>
                </value>
                <value>
                    <fullName>Finance/Gest./Adminis./Juridi.</fullName>
                </value>
                <value>
                    <fullName>Marketing/Communication</fullName>
                </value>
                <value>
                    <fullName>Organisation/Systèmes d&apos;Informations</fullName>
                </value>
                <value>
                    <fullName>Production/Achats</fullName>
                </value>
                <value>
                    <fullName>Ressources Humaines/Formation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pays__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adresse:Pays</label>
        <referenceTo>Pays__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect Etudiant</fullName>
                </value>
                <value>
                    <fullName>Etudiant</fullName>
                </value>
                <value>
                    <fullName>Professionnel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Professionnel</fullName>
        <active>true</active>
        <label>Professionnel</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cycle__c.object
<CustomObject>
    <label>Cycle</label>
    <nameField>
        <label>Code Centre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dipl_me__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Dipl_mes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cycle__c</fullName>
        <label>Cycle</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Programme__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>International MBA</fullName>
                </value>
                <value>
                    <fullName>CPA Lyon</fullName>
                </value>
                <value>
                    <fullName>Executive MBA</fullName>
                </value>
                <value>
                    <fullName>European Master in Management</fullName>
                </value>
                <value>
                    <fullName>Global Entrepreneurship Programme</fullName>
                </value>
                <value>
                    <fullName>MS Ingénierie Financière</fullName>
                </value>
                <value>
                    <fullName>MSc Luxury Mngt &amp; Mkt</fullName>
                </value>
                <value>
                    <fullName>MS Ingénierie et Internet</fullName>
                </value>
                <value>
                    <fullName>MS Acheteur Manager International</fullName>
                </value>
                <value>
                    <fullName>MS Management  Activités Industrielles</fullName>
                </value>
                <value>
                    <fullName>M.S. Mngt des Ent Vivant et de l&apos;agro.</fullName>
                </value>
                <value>
                    <fullName>MS Agro-Industriel</fullName>
                </value>
                <value>
                    <fullName>MS Audit et Information Financière</fullName>
                </value>
                <value>
                    <fullName>MS Conseil en Organisation</fullName>
                </value>
                <value>
                    <fullName>MS Stratégie et Dvpt d’Affaires Intl</fullName>
                </value>
                <value>
                    <fullName>MS Mgt et Dvpt Systèmes d&apos;Information</fullName>
                </value>
                <value>
                    <fullName>MS Entreprendre</fullName>
                </value>
                <value>
                    <fullName>MS Finance de Marché</fullName>
                </value>
                <value>
                    <fullName>MS GIRIS</fullName>
                </value>
                <value>
                    <fullName>MS Marketing Industriel</fullName>
                </value>
                <value>
                    <fullName>MS NTIC Management</fullName>
                </value>
                <value>
                    <fullName>MS Ingénierie et Mngt des SI</fullName>
                </value>
                <value>
                    <fullName>MS Juriste Manager International</fullName>
                </value>
                <value>
                    <fullName>MS Knowledge Management</fullName>
                </value>
                <value>
                    <fullName>MS Management des Entreprises de Service</fullName>
                </value>
                <value>
                    <fullName>M.S. Strat Internat et Marketing Indus</fullName>
                </value>
                <value>
                    <fullName>MS Management de la Technologie</fullName>
                </value>
                <value>
                    <fullName>Programme Général de Management</fullName>
                </value>
                <value>
                    <fullName>PhD in Management</fullName>
                </value>
                <value>
                    <fullName>MS Stratégie et Marketing des Entr. Ind.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Programme__c</fullName>
        <label>Programme</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MBA</fullName>
                </value>
                <value>
                    <fullName>CPA Lyon</fullName>
                </value>
                <value>
                    <fullName>Faculté</fullName>
                </value>
                <value>
                    <fullName>European Master in Management</fullName>
                </value>
                <value>
                    <fullName>ESC Lyon</fullName>
                </value>
                <value>
                    <fullName>MSc in Luxury Management et Marketing</fullName>
                </value>
                <value>
                    <fullName>Global Entrepreneurship Program</fullName>
                </value>
                <value>
                    <fullName>Mastères Spécialisés</fullName>
                </value>
                <value>
                    <fullName>Programme Général de Management</fullName>
                </value>
                <value>
                    <fullName>Msc in Sports Industry Management</fullName>
                </value>
                <value>
                    <fullName>MSc in Innovation,Design,Entrep. &amp; Arts</fullName>
                </value>
                <value>
                    <fullName>MSc in International Hospitality Management</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Promo_d_entr_e__c</fullName>
        <label>Promo d&apos;entrée</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promo_de_sortie__c</fullName>
        <label>Promo de sortie</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Diplômes EMLYON</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Numéro automatique</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diplômes EMLYON</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NAF__c.object
<CustomObject>
    <description>Une table de référence NAF/Code APE</description>
    <fields>
        <fullName>CODE_APE__c</fullName>
        <externalId>true</externalId>
        <label>CODE APE</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>NAF</label>
    <nameField>
        <label>Nom de NAF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pays__c.object
<CustomObject>
    <label>Pays</label>
    <nameField>
        <label>Nom de Pays</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestTR008ManageDiplomes.cls
@istest
public class TestTR008ManageDiplomes {
    
    static testMethod void majDateContact(){
        
        Pays__c pays = new Pays__c();
        pays.Name = 'France';
        insert pays;
        
        NAF__c naf = new NAF__c(Name='naf',CODE_APE__c='1234');
        insert naf;
        
        Account acc = new Account(Name='test');
        acc.SIRET__c='00000000000000';
        acc.CodeAPE__c=naf.Id;
        acc.Industry='Agriculture';
        acc.CodePays__c = pays.id;
        acc.Adresse_Ville__c = 'Nantes';
        insert acc;
        
        Contact contact1= new Contact(AccountId=acc.Id,
                                      statut__c='Professionnel',
                                      FirstName='Mahmoud',
                                      LastName='BECHAA',
                                      Salutation='M',
                                      Famille_Fonction__c='Autres');
        insert contact1;
        
        Contact contact2= new Contact(AccountId=acc.Id,
                                      statut__c='Professionnel',
                                      FirstName='Pierre',
                                      LastName='DURAND',
                                      Salutation='M',
                                      Famille_Fonction__c='Autres');
        insert contact2;
        
        Dipl_me__c dipl1 = new Dipl_me__c(programme__c='MBA', 
                                          Contact__c=contact1.id,
                                          Promo_d_entr_e__c='2015',
                                          Promo_de_sortie__c='2016',
                                          Cycle__c='International MBA'
        
        );
        Dipl_me__c dipl2 = new Dipl_me__c(programme__c='ESC Lyon', 
                                          Contact__c=contact2.id,
                                          Promo_d_entr_e__c='2015',
                                          Promo_de_sortie__c='2016'
        );
        
        insert dipl1;
        insert dipl2;
        
        List<Dipl_me__c> lDipl = New List<Dipl_me__c>();
        Set<Id> sContacts = new Set<Id>();
        
        lDipl.add(dipl1);
        lDipl.add(dipl2);
        
        // on initialise un tableau d'id des contacts dans lequel on stocke tous les contacts
        // auquel a été ajouté ou modifié un diplôme
        for(Dipl_me__c d : lDipl){
            
            sContacts.add(d.Contact__c);
            
        }
        
        // on parcours les contacts associés à chaque diplôme 
        // et on met à jour la date de modification avec la date du jour.
        List<Contact> lContacts = [select id, Date_Modification_Fiche__c  from contact where id in : sContacts];
        
        for(Contact c : lContacts){
            
            c.Date_Modification_Fiche__c = System.Date.today();
            
        }
        
        update lContacts;
        
        
         for(Contact c : lContacts){
            
            System.assertEquals(c.Date_Modification_Fiche__c, System.Date.today()) ;
            
        }
        
        
    }
    
}