objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adresse_Ville__c</fullName>
        <label>Adresse courante: Ville</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeAPE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NAF</label>
        <referenceTo>NAF__c</referenceTo>
        <relationshipLabel>Comptes</relationshipLabel>
        <relationshipName>Comptes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CodePays__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adresse courante: Pays</label>
        <referenceTo>Pays__c</referenceTo>
        <relationshipLabel>Comptes</relationshipLabel>
        <relationshipName>Comptes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIRET__c</fullName>
        <label>SIRET</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Adresse_Ville__c</fullName>
        <label>Adresse: Ville</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pays__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adresse:Pays</label>
        <referenceTo>Pays__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect Etudiant</fullName>
                </value>
                <value>
                    <fullName>Etudiant</fullName>
                </value>
                <value>
                    <fullName>Professionnel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Etudiant</fullName>
        <active>true</active>
        <label>Etudiant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Detail_pack__c.object
<CustomObject>
    <fields>
        <fullName>Composant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Composant</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Pack parent</relationshipLabel>
        <relationshipName>Composant_pack</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pack__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pack</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Détails pack</relationshipLabel>
        <relationshipName>Details_pack</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Détail pack</label>
    <nameField>
        <displayFormat>DP-{0}</displayFormat>
        <label>Id de Détail pack</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Détails pack</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Detail_pack_session__c.object
<CustomObject>
    <fields>
        <fullName>Composant_session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Composant session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Liste des sessions packs utilisant la session</relationshipLabel>
        <relationshipName>Details_pack_session</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pack_Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pack Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Détails des Sessions composant le pack</relationshipLabel>
        <relationshipName>Details_pack_session2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Détail pack session</label>
    <nameField>
        <displayFormat>DPS-{0}</displayFormat>
        <label>Nom de Détail pack session</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Détails pack session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NAF__c.object
<CustomObject>
    <description>Une table de référence NAF/Code APE</description>
    <fields>
        <fullName>CODE_APE__c</fullName>
        <externalId>true</externalId>
        <label>CODE APE</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>NAF</label>
    <nameField>
        <label>Nom de NAF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact_central__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact central</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunités</relationshipLabel>
        <relationshipName>Opportunites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exercice__c</fullName>
        <label>Exercice EMLYON</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2015</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Session_de_formation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Session de formation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ProduitFiltreSession__c</field>
                <operation>equals</operation>
                <valueField>Session__c.Produits__c</valueField>
            </filterItems>
            <filterItems>
                <field>Session__c.Statut__c</field>
                <operation>notEqual</operation>
                <value>Complète</value>
            </filterItems>
            <filterItems>
                <field>Session__c.Statut__c</field>
                <operation>notEqual</operation>
                <value>Abandonnée</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Liste prévisionnelle inscrit</relationshipLabel>
        <relationshipName>Poste_d_opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>TEXT(Opportunity.StageName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Statut</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Pays__c.object
<CustomObject>
    <label>Pays</label>
    <nameField>
        <label>Nom de Pays</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>Module</fullName>
        <active>true</active>
        <label>Module</label>
    </recordTypes>
    <recordTypes>
        <fullName>Pack</fullName>
        <active>true</active>
        <label>Pack</label>
    </recordTypes>
</CustomObject>

objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Code_agresso_for__c</fullName>
        <description>Ce champ va être renseigné manuellement ou par chargement et sert pour export vers AGRESSO en tant que code formation. Ex: 15SELPGM--1</description>
        <label>Code agresso Formation</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Produits__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Produit</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <picklist>
            <picklistValues>
                <fullName>SF-SS10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF-SS20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF-SS30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF-SS40</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Session de formation</label>
    <nameField>
        <label>Nom de Session</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions de formation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/test_TR_session_formation.cls
/**
LastModifiedBy Sabri Dali 17/03/2016
test class correction and assert implementation
cooments added
*/
@isTest
private class test_TR_session_formation {


 static testMethod void myUnitTest() {
  // get Product RecordTypes 
  String  pack = [select Id from RecordType  where DeveloperName = 'Pack' and SobjectType = 'Product2' limit 1].Id;
  String  Module = [select Id from RecordType  where DeveloperName = 'Module' and SobjectType = 'Product2' limit 1].Id;

  //date creation
  NAF__c naf = new NAF__c(Name='naf',CODE_APE__c='1234');
  insert naf;

  Pays__c pays = new Pays__c();
  pays.Name = 'France';
  insert pays;

  Account acc = new Account(Name='test');
  acc.SIRET__c='00000000000000';
  acc.CodeAPE__c=naf.Id;
  acc.Industry='Agriculture';
  acc.CodePays__c = pays.id;
  acc.Adresse_Ville__c = 'Nantes';
  insert acc;

  Contact contact= new Contact(AccountId=acc.Id,statut__c='Etudiant',FirstName='Asmae',LastName='Ettahiri',Salutation='Mme');
  insert contact;

  Product2 prod = new Product2(Name='prodTest', RecordtypeId = pack);
  insert prod;
  Product2 prod_module = new Product2(Name='prodTest', RecordtypeId = Module);
  insert prod_module;

  Detail_pack__c dp= new Detail_pack__c(Pack__c=prod.Id,Composant__c=prod_module.Id);
  insert dp;

  Session__c ses_pack = new Session__c (Name = 'pack', Produits__c = prod.Id, Code_agresso_for__c = '54983');
  insert ses_pack;
  Session__c ses_module = new Session__c (Name = 'module', Produits__c = prod_module.Id,  Code_agresso_for__c = '98456');
  insert ses_module;

  Detail_pack_session__c dps = new Detail_pack_session__c(Composant_session__c=ses_module.Id,Pack_Session__c=ses_pack.id);
  insert dps;

  // Get standard price book ID.
  // This is available irrespective of the state of SeeAllData.
  Id standardPB = Test.getStandardPricebookId();

  Pricebookentry pricebook1= new PriceBookEntry(Product2Id=prod.Id, UnitPrice=10, Pricebook2Id=standardPB, IsActive = true, UseStandardPrice = false);
  insert pricebook1;

  Pricebookentry pricebook2= new PriceBookEntry(Product2Id=prod_module.Id, UnitPrice=10, Pricebook2Id=standardPB, IsActive = true, UseStandardPrice = false);
  insert pricebook2;

  Date d = System.Today();
  Opportunity opp= new Opportunity(Pricebook2Id=standardPB,StageName='test',Name='test',Contact_central__c=contact.Id,AccountId=acc.Id,Exercice__c='2015',CloseDate=Date.valueOf('2015-08-15'));
  opp.CloseDate=Date.valueOf('2015-08-15');
  System.debug('#####CloseDate'+opp.CloseDate);
  insert opp;


  OpportunityLineItem oli = new OpportunityLineItem(PricebookentryId=pricebook1.Id, Totalprice=23, Quantity=2, Session_de_formation__c = ses_pack.Id, OpportunityId=opp.Id);

 // Test
  Test.startTest();
  insert oli;

  List<OpportunityLineItem> lcontrolOppLI = [select id,Session_de_formation__c from OpportunityLineItem where OpportunityId =: opp.Id and Session_de_formation__c =:ses_module.id];
  System.assert(lcontrolOppLI!=null);

  Test.stopTest();
 }
}