objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adresse_Ville__c</fullName>
        <label>Adresse courante: Ville</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeAPE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NAF</label>
        <referenceTo>NAF__c</referenceTo>
        <relationshipLabel>Comptes</relationshipLabel>
        <relationshipName>Comptes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CodePays__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adresse courante: Pays</label>
        <referenceTo>Pays__c</referenceTo>
        <relationshipLabel>Comptes</relationshipLabel>
        <relationshipName>Comptes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIRET__c</fullName>
        <label>SIRET</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Adresse_Ville__c</fullName>
        <label>Adresse: Ville</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pays__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adresse:Pays</label>
        <referenceTo>Pays__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect Etudiant</fullName>
                </value>
                <value>
                    <fullName>Etudiant</fullName>
                </value>
                <value>
                    <fullName>Professionnel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Etudiant</fullName>
        <active>true</active>
        <label>Etudiant</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Detail_pack__c.object
<CustomObject>
    <fields>
        <fullName>Composant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Composant</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Pack parent</relationshipLabel>
        <relationshipName>Composant_pack</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pack__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pack</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Détails pack</relationshipLabel>
        <relationshipName>Details_pack</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Détail pack</label>
    <nameField>
        <displayFormat>DP-{0}</displayFormat>
        <label>Id de Détail pack</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Détails pack</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NAF__c.object
<CustomObject>
    <description>Une table de référence NAF/Code APE</description>
    <fields>
        <fullName>CODE_APE__c</fullName>
        <externalId>true</externalId>
        <label>CODE APE</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>NAF</label>
    <nameField>
        <label>Nom de NAF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact_central__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact central</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunités</relationshipLabel>
        <relationshipName>Opportunites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exercice__c</fullName>
        <label>Exercice EMLYON</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2015</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Statut__c</fullName>
        <formula>TEXT(Opportunity.StageName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Statut</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Pays__c.object
<CustomObject>
    <label>Pays</label>
    <nameField>
        <label>Nom de Pays</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Suiveur__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suiveur</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Produits</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Pack</fullName>
        <active>true</active>
        <label>Pack</label>
    </recordTypes>
</CustomObject>

classes/TestTR005OppLineItem.cls
/**
LastModifiedBy Sabri Dali 16/03/2016
test class correction and assert implementation
cooments added
*/
@isTest
private class TestTR005OppLineItem {

 static testMethod void myUnitTest() {
            
  //Get Product RecordType
  String  pack = [select Id from RecordType  where DeveloperName = 'Pack' and SobjectType = 'Product2' limit 1].Id;

  //Data creation
  NAF__c naf = new NAF__c(Name='naf',CODE_APE__c='1234');
  insert naf;

  Pays__c pays = new Pays__c();
  pays.Name = 'France';
  insert pays;

  Account acc = new Account(Name='test');
  acc.SIRET__c='00000000000000';
  acc.CodeAPE__c=naf.Id;
  acc.Industry='Agriculture';
  acc.CodePays__c = pays.id;
  acc.Adresse_Ville__c = 'Nantes';
  insert acc;

  Contact contact= new Contact(AccountId=acc.Id,statut__c='Etudiant',FirstName='Asmae',LastName='Ettahiri',Salutation='Mme');
  insert contact;

  Product2 prod = new Product2(Name='prodTest',RecordtypeId = pack);
  insert prod;

     RecordType rtProd = [SELECT Id, name FROM RecordType WHERE DeveloperName = 'Pack'];
      Product2 prod_1 = new Product2(Name='prodTest', Suiveur__c = UserInfo.getUserId(),RecordTypeId =rtProd.id);
     
     insert prod_1;
     
     Product2 prod2 = new Product2(Name='prodTest',Suiveur__c = UserInfo.getUserId(),RecordTypeId =rtProd.id);
  insert prod2;

  Detail_pack__c dp= new Detail_pack__c(Pack__c=prod.Id,Composant__c=prod2.Id);
  insert dp;
   
     Detail_pack__c dp1= new Detail_pack__c(Pack__c=prod2.Id,Composant__c=prod_1.Id);
     

  // Get standard price book ID.
  // This is available irrespective of the state of SeeAllData.
  Id standardPB = Test.getStandardPricebookId();

  Pricebookentry pricebook1= new PriceBookEntry(Product2Id=prod.Id, UnitPrice=10, Pricebook2Id=standardPB, IsActive = true, UseStandardPrice = false);
  insert pricebook1;

  Pricebookentry pricebook2= new PriceBookEntry(Product2Id=prod2.Id, UnitPrice=10, Pricebook2Id=standardPB, IsActive = true, UseStandardPrice = false);
  insert pricebook2;
     
      Pricebookentry pricebook3= new PriceBookEntry(Product2Id=prod_1.Id, UnitPrice=10, Pricebook2Id=standardPB, IsActive = true, UseStandardPrice = false);
  insert pricebook3;

  Date d = System.Today();
  Opportunity opp= new Opportunity(Pricebook2Id=standardPB ,StageName='test',Name='test',Contact_central__c=contact.Id,AccountId=acc.Id,Exercice__c='2015',CloseDate=Date.valueOf('2015-08-15'));
  opp.CloseDate=Date.valueOf('2015-08-15');
  System.debug('#####CloseDate'+opp.CloseDate);
  insert opp;

     List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();

   
    //insert oli;   
      for (Integer i =0;i<200;i++){
          OpportunityLineItem oli = new OpportunityLineItem(PricebookentryId=pricebook2.Id, Totalprice=23, Quantity=2,Product2Id =prod2.Id);     
  	      oli.OpportunityId=opp.Id;
          oliList.add(oli);
      }
   INSERT oliList;
  //Test
  Test.startTest();    
  OpportunityLineItem controlOppLI = [select id from OpportunityLineItem where OpportunityId =: opp.Id and Product2Id =:prod2.Id Limit 1];
  System.assert(controlOppLI!=null);
  Test.stopTest(); 
     
 }
}