objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adresse_Ville__c</fullName>
        <label>Adresse courante: Ville</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeAPE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NAF</label>
        <referenceTo>NAF__c</referenceTo>
        <relationshipLabel>Comptes</relationshipLabel>
        <relationshipName>Comptes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CodePays__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adresse courante: Pays</label>
        <referenceTo>Pays__c</referenceTo>
        <relationshipLabel>Comptes</relationshipLabel>
        <relationshipName>Comptes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SIRET__c</fullName>
        <label>SIRET</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Adresse_Ville__c</fullName>
        <label>Adresse: Ville</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Famille_Fonction__c</fullName>
        <label>Famille Fonction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Autres</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Commercial/Ventes</fullName>
                </value>
                <value>
                    <fullName>Direction Générale</fullName>
                </value>
                <value>
                    <fullName>Enseignement/Education</fullName>
                </value>
                <value>
                    <fullName>Etud/Recherche/Dévelop/Qualité</fullName>
                </value>
                <value>
                    <fullName>Finance/Gest./Adminis./Juridi.</fullName>
                </value>
                <value>
                    <fullName>Marketing/Communication</fullName>
                </value>
                <value>
                    <fullName>Organisation/Systèmes d&apos;Informations</fullName>
                </value>
                <value>
                    <fullName>Production/Achats</fullName>
                </value>
                <value>
                    <fullName>Ressources Humaines/Formation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pays__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adresse:Pays</label>
        <referenceTo>Pays__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect Etudiant</fullName>
                </value>
                <value>
                    <fullName>Etudiant</fullName>
                </value>
                <value>
                    <fullName>Professionnel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Etudiant</fullName>
        <active>true</active>
        <label>Etudiant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Professionnel</fullName>
        <active>true</active>
        <label>Professionnel</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NAF__c.object
<CustomObject>
    <description>Une table de référence NAF/Code APE</description>
    <fields>
        <fullName>CODE_APE__c</fullName>
        <externalId>true</externalId>
        <label>CODE APE</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Code_NACE__c</fullName>
        <label>Code NACE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secteur__c</fullName>
        <label>Secteur</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NAF</label>
    <nameField>
        <label>Nom de NAF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pays__c.object
<CustomObject>
    <label>Pays</label>
    <nameField>
        <label>Nom de Pays</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Postes_Suppl_mentaires__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Postes_Suppl_mentaires</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Famille_Fonction__c</fullName>
        <label>Famille Fonction</label>
        <picklist>
            <picklistValues>
                <fullName>Autres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direction Générale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production/Achats</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Etud/Recherche/Dévelop/Qualité</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ressources Humaines/Formation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing/Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial/Ventes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance/Gest./Adminis./Juridi.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organisation/Systèmes d&apos;Informations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enseignement/Education</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Historique poste et poste supplémentaire</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Nom de Postes Supplémentaires</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historique poste et poste supplémentaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestTR001ManageContact.cls
/**
LastModifiedBy Sabri Dali 16/03/2016
test class correction and assert implementation
cooments added
*/
@isTest
public class TestTR001ManageContact {

    static testMethod void verifyCreatePosteSupplementaire(){

        //Data creation
        NAF__c naf = new NAF__c();
        naf.CODE_APE__c = 'AAAA';
        naf.Code_NACE__c = 'BBBB';
        naf.Secteur__c = 120;
        insert naf;

        Pays__c pays = new Pays__c();
        pays.Name = 'France';
        insert pays;

        Account acc1 = new Account(Name='AccTest1');
        acc1.SIRET__c  = '40483304800022';
        acc1.CodeAPE__c = naf.Id;
        acc1.CodePays__c = pays.id;
        acc1.Adresse_Ville__c = 'Nantes';
        insert acc1;

        Account acc2 = new Account(Name='AccTest2');
        acc2.SIRET__c  = '40483304800030';
        acc2.CodeAPE__c = naf.Id;
        acc2.CodePays__c = pays.id;
        acc2.Adresse_Ville__c = 'Nantes';
        insert acc2;

        Contact testContact = new Contact();
        testContact.lastName = 'toto';
        testContact.firstName = 'toto2';
        testContact.salutation = 'M.';
        testContact.AccountId = acc1.Id;
        testContact.Statut__c = 'Etudiant';
        testContact.Famille_Fonction__c = 'Production/Achats';
        insert testContact;

        //Test
        Test.startTest();
        testContact.AccountId = acc2.Id;
        testContact.Statut__c = 'Professionnel';
        update testContact;
        List<Postes_Suppl_mentaires__c> poste = [SELECT id,Name FROM Postes_Suppl_mentaires__c where Contact__c =:testContact.Id];
        System.assertEquals(1, poste.size());
        Test.stopTest();
    }
}