objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adresse_Ville__c</fullName>
        <label>Adresse courante: Ville</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeAPE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NAF</label>
        <referenceTo>NAF__c</referenceTo>
        <relationshipLabel>Comptes</relationshipLabel>
        <relationshipName>Comptes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CodePays__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adresse courante: Pays</label>
        <referenceTo>Pays__c</referenceTo>
        <relationshipLabel>Comptes</relationshipLabel>
        <relationshipName>Comptes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Est_un_OCTA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indique si ce compte est un OCTA</description>
        <label>Est un OCTA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SIRET__c</fullName>
        <label>SIRET</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NAF__c.object
<CustomObject>
    <description>Une table de référence NAF/Code APE</description>
    <fields>
        <fullName>CODE_APE__c</fullName>
        <externalId>true</externalId>
        <label>CODE APE</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>NAF</label>
    <nameField>
        <label>Nom de NAF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Exercice__c</fullName>
        <label>Exercice EMLYON</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2015</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OCTA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCTA supposé</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Est_un_OCTA__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Taxe Opportunités</relationshipLabel>
        <relationshipName>Opportunites</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Taxe</fullName>
        <active>true</active>
        <businessProcess>Taxe</businessProcess>
        <description>Taxe d&apos;apprentissage</description>
        <label>Taxe</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>OCTA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCTA</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Est_un_OCTA__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Poste d&apos;opportunité</relationshipLabel>
        <relationshipName>Poste_d_opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Pays__c.object
<CustomObject>
    <label>Pays</label>
    <nameField>
        <label>Nom de Pays</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>Taxe</fullName>
        <active>true</active>
        <label>Taxe</label>
    </recordTypes>
</CustomObject>

classes/TestTR006OppLineItem2FieldsNull.cls
@isTest
public class TestTR006OppLineItem2FieldsNull {
    
    static testMethod void myUnitTest() {
        try{
             // Data creation
        NAF__c naf = new NAF__c(Name = 'naf', CODE_APE__c = '1234');
        insert naf;
        
        Pays__c pays = new Pays__c();
        pays.Name = 'France';
        insert pays;
        
        Account acc = new Account();
        acc.Name = 'test';
        acc.SIRET__c = '00000000000000';
        acc.CodeAPE__c = naf.Id;
        acc.Industry = 'Agriculture';
        acc.CodePays__c = pays.id;
        acc.Adresse_Ville__c = 'Nantes';
        acc.Est_un_OCTA__c = true;
        insert acc; 

        Product2 prod = new Product2();
        prod.Name = 'prodTest';
        insert prod;
        
        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id standardPbId = Test.getStandardPricebookId();
        
        Pricebookentry pricebook1 = new PriceBookEntry();
        pricebook1.Product2Id = prod.Id;
        pricebook1.UnitPrice = 10;
        pricebook1.Pricebook2Id = standardPbId;
        pricebook1.IsActive = true;
        pricebook1.UseStandardPrice = false ;
        insert pricebook1;
        
        Date d = System.Today();
        Opportunity opp = new Opportunity();
        opp.StageName = 'test';
        opp.Name = 'test';
        opp.AccountId = acc.Id;
        opp.Exercice__c = '2015';
        opp.CloseDate = Date.valueOf('2015-08-15');
        opp.RecordTypeId = [SELECT Id, sObjectType FROM RecordType WHERE DeveloperName = 'Taxe' AND sObjectType = 'Opportunity'].Id;
        insert opp;
        
        System.debug('RECORD TYPE : ' + opp.RecordTypeId);
        
        List<OpportunityLineItem> oppLines = new List<OpportunityLineItem>();
        OpportunityLineItem oli_00 = new OpportunityLineItem();
        oli_00.PricebookentryId = pricebook1.Id;
        oli_00.Totalprice = 23;
        oli_00.OpportunityId = opp.Id;
        // oli_00.Description = 'toto';
        oppLines.add(oli_00);
        
        OpportunityLineItem oli_01 = new OpportunityLineItem();
        oli_01.PricebookentryId = pricebook1.Id;
        oli_01.Totalprice = 23;
        oli_01.OpportunityId = opp.Id;
        // oli_01.OCTA__c = acc.Id;
        oppLines.add(oli_01);
        
        OpportunityLineItem oli_02 = new OpportunityLineItem();
        oli_02.PricebookentryId = pricebook1.Id;
        oli_02.Totalprice = 23;
        oli_02.OpportunityId = opp.Id;
        oli_02.Description = 'toto';
        oli_02.OCTA__c = acc.Id;
        oppLines.add(oli_02);
        
        // Test
        Test.startTest();
        // Insertion des Lignes Produits
        insert oppLines;
        // Re-lecture des Lignes Produits
        List<OpportunityLineItem> oppLine = [SELECT Quantity, Description, OCTA__c FROM OpportunityLineItem WHERE Id = :oppLines];
                System.assertEquals(3, oppLine.size());
        for(OpportunityLineItem oli : oppLine) {
         // mis en commentaire suite à erreur lors des déploiements en production
         // System.assertEquals('toto', oli.Description);
         //   System.assertEquals(acc.Id, oli.OCTA__c);
        }
        Test.stopTest();
            
        }
        catch(Exception e)
        {System.debug(' The following exception has occurred: ' + e.getMessage());}
       
        
       

    }
}