objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Etat__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adresse: Etat</label>
        <referenceTo>Etat__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Etat__c.object
<CustomObject>
    <label>Etat</label>
    <nameField>
        <label>Nom de Etat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Etats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Portefeuille_contacts__c.object
<CustomObject>
    <description>Liste les utilisateurs internes en lien avec un contact via : la création du contact, une opportunité créée sur le contact, ou une activité créée sur le contact.</description>
    <label>Relation avec le contact</label>
    <nameField>
        <displayFormat>PC-{0000000000}</displayFormat>
        <label>Relation avec le contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relations avec le contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Session__c.object
<CustomObject>
    <label>Session de formation</label>
    <nameField>
        <label>Nom de Session</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions de formation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DataExtract022Event.cls
/**
 * Created by Julie NGUYEN - Modis on 07/03/2017.
 */

public class DataExtract022Event implements Queueable {

    public static String OBJECT_NAME_EVENT = 'Event';

    private DataToExport dataExport;

    public DataExtract022Event(DataToExport dataToExport) {
        this.dataExport = dataToExport;
    }

    public void execute(QueueableContext context) {
        extractEvents();
        if ( !Test.isRunningTest() ) {
            System.enqueueJob(new DataExtract023ContactAssoOpp(dataExport));
        }
    }

    /**
    Extraction des événements reliés aux enregistrements déjà traités parmi les objets :
    - Contact
    - Account
    - Portefeuille_contacts__c
    - Etat__c
    - Lead
    - Opportunity
    - Product2
    - Session__c
     */
    public void extractEvents() {
        System.debug('--- BEGIN DataExtract022Event / extractEvents() ---');
        String whoIdClause = ' WHERE ((';

        if ( dataExport.contactsToExport != null && !dataExport.contactsToExport.isEmpty() ) {
            whoIdClause += ' WhoId IN ' + DataExtractUtils.convertSetToString(dataExport.contactsToExport);
        }

        if ( dataExport.accountsToExport != null && !dataExport.accountsToExport.isEmpty() ) {
            whoIdClause += ' OR WhoId IN ' + DataExtractUtils.convertSetToString(dataExport.accountsToExport);
        }

        if ( dataExport.portefeuillesToExport != null && !dataExport.portefeuillesToExport.isEmpty() ) {
            whoIdClause += ' OR WhoId IN ' + DataExtractUtils.convertSetToString(dataExport.portefeuillesToExport);
        }

        if ( dataExport.etatsToExport != null && !dataExport.etatsToExport.isEmpty() ) {
            whoIdClause += ' OR WhoId IN ' + DataExtractUtils.convertSetToString(dataExport.etatsToExport);
        }

        if ( dataExport.leadsToExport != null && !dataExport.leadsToExport.isEmpty() ) {
            whoIdClause += ' OR WhoId IN ' + DataExtractUtils.convertSetToString(dataExport.leadsToExport);
        }

        if ( dataExport.opportunitiesToExport != null && !dataExport.opportunitiesToExport.isEmpty() ) {
            whoIdClause += ' OR WhoId IN ' + DataExtractUtils.convertSetToString(dataExport.opportunitiesToExport);
        }

        if ( dataExport.productsToExport != null && !dataExport.productsToExport.isEmpty() ) {
            whoIdClause += ' OR WhoId IN ' + DataExtractUtils.convertSetToString(dataExport.productsToExport);
        }

        if ( dataExport.sessionsToExport != null && !dataExport.sessionsToExport.isEmpty() ) {
            whoIdClause += ' OR WhoId IN ' + DataExtractUtils.convertSetToString(dataExport.sessionsToExport);
        }

        whoIdClause += ') ';

        System.debug('-- PARAM String whoIdClause : ' + whoIdClause);

        String whatIdClause = ' OR (';

        if ( dataExport.contactsToExport != null && !dataExport.contactsToExport.isEmpty() ) {
            whatIdClause += ' WhatId IN ' + DataExtractUtils.convertSetToString(dataExport.contactsToExport);
        }

        if ( dataExport.accountsToExport != null && !dataExport.accountsToExport.isEmpty() ) {
            whatIdClause += ' OR WhatId IN ' + DataExtractUtils.convertSetToString(dataExport.accountsToExport);
        }

        if ( dataExport.portefeuillesToExport != null && !dataExport.portefeuillesToExport.isEmpty() ) {
            whatIdClause += ' OR WhatId IN ' + DataExtractUtils.convertSetToString(dataExport.portefeuillesToExport);
        }

        if ( dataExport.etatsToExport != null && !dataExport.etatsToExport.isEmpty() ) {
            whatIdClause += ' OR WhatId IN ' + DataExtractUtils.convertSetToString(dataExport.etatsToExport);
        }

        if ( dataExport.leadsToExport != null && !dataExport.leadsToExport.isEmpty() ) {
            whatIdClause += ' OR WhatId IN ' + DataExtractUtils.convertSetToString(dataExport.leadsToExport);
        }

        if ( dataExport.opportunitiesToExport != null && !dataExport.opportunitiesToExport.isEmpty() ) {
            whatIdClause += ' OR WhatId IN ' + DataExtractUtils.convertSetToString(dataExport.opportunitiesToExport);
        }

        if ( dataExport.productsToExport != null && !dataExport.productsToExport.isEmpty() ) {
            whatIdClause += ' OR WhatId IN ' + DataExtractUtils.convertSetToString(dataExport.productsToExport);
        }

        if ( dataExport.sessionsToExport != null && !dataExport.sessionsToExport.isEmpty() ) {
            whatIdClause += ' OR WhatId IN ' + DataExtractUtils.convertSetToString(dataExport.sessionsToExport);
        }

        whatIdClause += ' )) ';

        System.debug('-- PARAM String whatIdClause : ' + whatIdClause);

        // Set qui contient les champs à ne pas prendre en compte pour l'extraction
        Set<String> fieldNamesNotToExport = new Set<String>{'WhatId','WhoId'};

        String techIdClause = ' AND (TECH_External_Who_Id__c != null OR TECH_External_What_Id__c != null) ';

        DataExtractUtils.extractFieldsWithExceptionsToCSV('17', OBJECT_NAME_EVENT, fieldNamesNotToExport,
                whoIdClause + whatIdClause + techIdClause, null);

        System.debug('--- END DataExtract022Event / extractEvents() ---');
    }

}