objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Date_de_d_but__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_de_fin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Professionnel__c</fullName>
        <label>Email Professionnel(ne pas utilisé)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_de_repli__c</fullName>
        <label>Email Professionnel</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Famille_Fonction__c</fullName>
        <label>Famille Fonction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Autres</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Commercial/Ventes</fullName>
                </value>
                <value>
                    <fullName>Direction Générale</fullName>
                </value>
                <value>
                    <fullName>Enseignement/Education</fullName>
                </value>
                <value>
                    <fullName>Etud/Recherche/Dévelop/Qualité</fullName>
                </value>
                <value>
                    <fullName>Finance/Gest./Adminis./Juridi.</fullName>
                </value>
                <value>
                    <fullName>Marketing/Communication</fullName>
                </value>
                <value>
                    <fullName>Organisation/Systèmes d&apos;Informations</fullName>
                </value>
                <value>
                    <fullName>Production/Achats</fullName>
                </value>
                <value>
                    <fullName>Ressources Humaines/Formation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fonctions__c</fullName>
        <label>Fonction codée</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Famille_Fonction__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Président(e)</fullName>
                </value>
                <value>
                    <fullName>Administrateur</fullName>
                </value>
                <value>
                    <fullName>Vice-Président</fullName>
                </value>
                <value>
                    <fullName>Président du Directoire</fullName>
                </value>
                <value>
                    <fullName>Conseiller du Président</fullName>
                </value>
                <value>
                    <fullName>Président Directeur Général</fullName>
                </value>
                <value>
                    <fullName>Directeur Général</fullName>
                </value>
                <value>
                    <fullName>Directeur Général Adjoint</fullName>
                </value>
                <value>
                    <fullName>Secrétaire Général</fullName>
                </value>
                <value>
                    <fullName>Directeur du Développement</fullName>
                </value>
                <value>
                    <fullName>Directeur Affaires Internationales</fullName>
                </value>
                <value>
                    <fullName>Fondé de Pouvoir</fullName>
                </value>
                <value>
                    <fullName>Dir. des Compensations Internationales</fullName>
                </value>
                <value>
                    <fullName>Directeur</fullName>
                </value>
                <value>
                    <fullName>Directeur Adjoint</fullName>
                </value>
                <value>
                    <fullName>Attaché de Direction</fullName>
                </value>
                <value>
                    <fullName>Directeur de Filiale</fullName>
                </value>
                <value>
                    <fullName>Directeur et Responsable d&apos;Etablissement</fullName>
                </value>
                <value>
                    <fullName>Associé</fullName>
                </value>
                <value>
                    <fullName>Gérant(e)</fullName>
                </value>
                <value>
                    <fullName>Directeur d&apos;Agence</fullName>
                </value>
                <value>
                    <fullName>Conseil Auprès de la DG</fullName>
                </value>
                <value>
                    <fullName>Directeur ou Conseil en Stratégie</fullName>
                </value>
                <value>
                    <fullName>Chargé de Mission</fullName>
                </value>
                <value>
                    <fullName>Directeur Technique</fullName>
                </value>
                <value>
                    <fullName>Responsable Technique</fullName>
                </value>
                <value>
                    <fullName>Cadre Technique</fullName>
                </value>
                <value>
                    <fullName>Personnel Technique</fullName>
                </value>
                <value>
                    <fullName>Cadre Logistique</fullName>
                </value>
                <value>
                    <fullName>Directeur  Logistique</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mobile_professionnel__c</fullName>
        <label>Mobile professionnel</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>parti_de_l_entreprise__c</fullName>
        <defaultValue>false</defaultValue>
        <label>parti de l&apos;entreprise</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Postes_Suppl_mentaires__c.object
<CustomObject>
    <fields>
        <fullName>Compte__c</fullName>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Postes_Suppl_mentaires</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Postes_Suppl_mentaires</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_de_d_but_du_poste__c</fullName>
        <label>Date de début du poste</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_de_fin_du_poste__c</fullName>
        <label>Date de fin du poste</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Professionnel__c</fullName>
        <label>Email Professionnel</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Famille_Fonction__c</fullName>
        <label>Famille Fonction</label>
        <picklist>
            <picklistValues>
                <fullName>Autres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direction Générale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production/Achats</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Etud/Recherche/Dévelop/Qualité</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ressources Humaines/Formation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing/Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial/Ventes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance/Gest./Adminis./Juridi.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organisation/Systèmes d&apos;Informations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enseignement/Education</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fonction_exacte__c</fullName>
        <label>Fonction exacte</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fonctions__c</fullName>
        <label>Fonction codée</label>
        <picklist>
            <controllingField>Famille_Fonction__c</controllingField>
            <picklistValues>
                <fullName>Non Renseignée</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof Libérales &amp; Act.Diverses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>En Cours de Création d&apos;Entreprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volontariat International en Entreprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>En Cours de Formation Compl.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retraité(e)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congé Parental d&apos;Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Militaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profession Artistique</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof Médicale/Pharmacie/Vétér.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Religieux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ministre/Député/Haut Fonction.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cadre des Services Publics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exploitant Agricole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Journaliste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contrôleur/Inspecteur Impôts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syndic d&apos;Immeubles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hôtelier/Restaurateur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commerçant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent(Général) d&apos;Assurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divers Etranger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direction Générale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrateur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Président(e)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vice-Président</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conseiller du Président</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Président du Directoire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Président Directeur Général</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Directeur Général</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mobile_professionnel__c</fullName>
        <label>Mobile professionnel</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Parti_de_l_entreprise__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Parti de l&apos;entreprise</label>
        <type>Checkbox</type>
    </fields>
    <label>Historique poste et poste supplémentaire</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Nom de Postes Supplémentaires</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historique poste et poste supplémentaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TR001ManageContact.cls
public class TR001ManageContact {

    // Fonction de création d’un enregistrement « poste supplémentaire »
    public static void CreatePosteSupplementaire(List <Contact> ContactsOld, List <Contact> ContactsNew){
        Set<String> DevsNot2execSet = new Set<String>();
        DevsNot2execSet.add('TR001ManageContact');
        Pad.doNotExecuteAfterMe(DevsNot2execSet);
        
        // Déclaration de la liste qui va contenir les postes à créer
        list<Postes_Suppl_mentaires__c> posteList = new list<Postes_Suppl_mentaires__c>();
        
        Integer i = 0;
        for(Contact c : ContactsOld){
            // Condition ci-dessous ajoutée le 25/11/2016 afin d'éviter une erreur
            // lorsque le contact ne possède pas de compte associé
            if(c.AccountId!=null){
                Postes_Suppl_mentaires__c poste = new Postes_Suppl_mentaires__c();
                
                poste.Compte__c = c.AccountId;
                poste.Famille_Fonction__c = c.Famille_Fonction__c;
                poste.Fonctions__c = c.Fonctions__c;
                poste.Fonction_exacte__c = c.title;
                poste.Date_de_d_but_du_poste__c = c.Date_de_d_but__c;
                poste.Date_de_fin_du_poste__c = (c.Date_de_fin__c != null ? c.Date_de_fin__c : Date.today());
                poste.Email_Professionnel__c = c.Email_de_repli__c;
                poste.Mobile_professionnel__c = c.Mobile_professionnel__c;
                poste.Parti_de_l_entreprise__c = (ContactsOld[i].AccountId != ContactsNew[i].AccountId ? true : false);
                poste.Contact__c = c.id;
                
                i++;
                posteList.add(poste);
            }
        }
        
        // Persistence
        // Condition ci-dessous ajoutée le 25/11/2016 
        if(posteList.size()>0){
            insert posteList;
        }
    }
}