objects/Etablissement__c.object
<CustomObject>
    <fields>
        <fullName>TECH_External_Id__c</fullName>
        <description>Champ technique qui contient la copie de l&apos;Id de l&apos;enregistrement 
en production</description>
        <externalId>true</externalId>
        <label>TECH_External_Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Etablissement</label>
    <nameField>
        <label>Nom de Etablissement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Etablissement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchFillTechId005Etablissement.cls
/**
 * Created by Julie NGUYEN - Modis on 08/03/2017.
 * Classe servant au remplissage du champ TECH_External_Id__c
 * Sa classe de test est : TestBatchFillTechIdObjects
 */

global class BatchFillTechId005Etablissement implements Database.Batchable<sObject> {
    String query = 'SELECT Id FROM Etablissement__c WHERE Tech_External_Id__c = null';

    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('--- BEGIN BatchFillTechId005Etablissement ---');
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Etablissement__c> records){
        System.debug('--- Execute part BatchFillTechId005Etablissement ---');
        for (Etablissement__c etablissement : records) {
            etablissement.TECH_External_Id__c = etablissement.Id;
        }
        Database.update(records, false);
    }

    global void finish(Database.BatchableContext bc){
        System.debug('--- END BatchFillTechId005Etablissement ---');
        if(!Test.isRunningTest()){
            Database.executeBatch(new BatchFillTechId006Pays());
        }
    }

}