objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Session_de_formation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Session de formation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ProduitFiltreSession__c</field>
                <operation>equals</operation>
                <valueField>Session__c.Produits__c</valueField>
            </filterItems>
            <filterItems>
                <field>Session__c.Statut__c</field>
                <operation>notEqual</operation>
                <value>Complète</value>
            </filterItems>
            <filterItems>
                <field>Session__c.Statut__c</field>
                <operation>notEqual</operation>
                <value>Abandonnée</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Liste prévisionnelle inscrit</relationshipLabel>
        <relationshipName>Poste_d_opportunit</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Session_de_formation_associee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Session de formation associée</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Sessions de formation</relationshipLabel>
        <relationshipName>Sessions_de_formation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session de formation</label>
    <nameField>
        <label>Nom de Session</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions de formation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TR_session_formation.cls
public with sharing class TR_session_formation{

public static void attach_session(list<OpportunityLineItem > po_module, Map<Id,Session__c > map_session){
list<OpportunityLineItem> poToUpdate;
//[select Id, Name from Session__c  where Session_de_formation_associee__c IN :Id_sess]
for(OpportunityLineItem po: po_module)
 {
 
  if(map_session.ContainsKey(po.PricebookEntry.Product2Id) )
  {
  po.Session_de_formation__c = map_session.get(po.PricebookEntry.Product2Id).Id;
  // poToUpdate.add(po);
  }

 }
 update po_module;
 
 }
}