objects/Partenaire_financeur__c.object
<CustomObject>
    <fields>
        <fullName>Compte_financeur__c</fullName>
        <label>Compte financeur</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partenaires_financeurs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Opportunite_financee__c</fullName>
        <label>Opportunité financée</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Partenaires_financeurs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partenaire financeur / collecteur OPCA</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partenaires financeurs/ collecteurs OPCA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DataExtract024PartenaireFinanceur.cls
/**
 * Created by Julie NGUYEN - Modis on 07/03/2017.
 */

public class DataExtract024PartenaireFinanceur implements Queueable {

    public static final String OBJECT_NAME_PARTENAIRE_FINANCEUR = 'Partenaire_financeur__c';

    private DataToExport dataExport;

    public DataExtract024PartenaireFinanceur(DataToExport dataToExport) {
        this.dataExport = dataToExport;
    }

    public void execute(QueueableContext context) {
        extractPartenairesFinanceurs();
        if ( !Test.isRunningTest() ) {
            System.enqueueJob(new DataExtract025MailingAfterExtract());
        }
    }

    /**
    Extraction des partenaires financeurs reliés aux enregistrements déjà traités parmi les objets :
    - Account
    - Opportunity
     */
    public void extractPartenairesFinanceurs() {
        System.debug('--- BEGIN DataExtract024PartenaireFinanceur / extractPartenairesFinanceurs() ---');

        if ( ( dataExport.accountsToExport != null && !dataExport.accountsToExport.isEmpty() ) &&
                ( dataExport.opportunitiesToExport != null && !dataExport.opportunitiesToExport.isEmpty() ) ) {
            String clause = ' WHERE Compte_financeur__c IN ' + DataExtractUtils.convertSetToString(dataExport.accountsToExport) +
                    ' AND Opportunite_financee__c IN ' + DataExtractUtils.convertSetToString(dataExport.opportunitiesToExport)
            ;

            System.debug('-- PARAM String clause : ' + clause);

            DataExtractUtils.extractAllFieldWithSpecificWhereClause('20', OBJECT_NAME_PARTENAIRE_FINANCEUR, clause);
        } else {
            System.debug('Il n\'y a pas de comptes associés à des opportunités parmi les comptes et les ' +
                    'opportunités déjà traités');
        }

        System.debug('--- END DataExtract024PartenaireFinanceur / extractPartenairesFinanceurs() ---');
    }

}