objects/Titre__c.object
<CustomObject>
    <fields>
        <fullName>TECH_External_Id__c</fullName>
        <description>Champ technique qui contient la copie de l&apos;Id de l&apos;enregistrement 
en production</description>
        <externalId>true</externalId>
        <label>TECH_External_Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Titre</label>
    <nameField>
        <label>Nom de Titre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titre</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DataExtract001Titre.cls
/**
 * Created by Julie NGUYEN - Modis on 13/02/2017.
 */

public class DataExtract001Titre implements Queueable {

    public static final String OBJECT_NAME_TITRE = 'Titre__c';

    public void execute(QueueableContext context) {
        extractTitres();
        if(!Test.isRunningTest()) {
            System.enqueueJob(new DataExtract003Naf());
        }
    }

    /**
    Extraction de tous les enregistrements "Titre__c"
     */
    public static void extractTitres() {
        System.debug('--- Begin DataExtract001Titre / extractTitres() ---');
        String whereClause = ' WHERE TECH_External_ID__c != null';
        DataExtractUtils.extractAllFieldWithSpecificWhereClause('01', OBJECT_NAME_TITRE, whereClause);
        System.debug('--- End DataExtract001Titre / extractTitres() ---');
    }
}