objects/User.object
<CustomObject>
    <fields>
        <fullName>ByPass_RV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ByPass RV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BypassTrigger__c</fullName>
        <label>BypassTrigger</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TR001ManageContact</fullName>
                </value>
                <value>
                    <fullName>TR002ManageOpportunityLineItem</fullName>
                </value>
                <value>
                    <fullName>TR003ManageOpportunities</fullName>
                </value>
                <value>
                    <fullName>TR004ManageLead</fullName>
                </value>
                <value>
                    <fullName>TR005OppLineItem</fullName>
                </value>
                <value>
                    <fullName>TR_session_formation</fullName>
                </value>
                <value>
                    <fullName>TR006OppLineItem2FieldsNull</fullName>
                </value>
                <value>
                    <fullName>TR007Opp2FieldsNull</fullName>
                </value>
                <value>
                    <fullName>EventTriggerHandler</fullName>
                </value>
                <value>
                    <fullName>TaskTriggerHandler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_Utils.cls
@isTest
public class Test_Utils {

    // Méthode de création d'un utilisateur de test 
    public static User createTestUser (string bypassTriggers, boolean bypassWorkflow, boolean bypassValidationRules) {        
        User testUser = new User(
            alias = 'Test',
            email = 'test_emlyon@example.com', 
            emailencodingkey='UTF-8',
            lastname='EML',
            languagelocalekey='fr', 
            localesidkey='fr_FR',
            profileid = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = 'Administrateur système' LIMIT 1][0].Id,
            timezonesidkey='America/Los_Angeles',
            username='test_emlyon@example.com',
            BypassTrigger__c = bypassTriggers,
            //Bypass_Workflows__c = bypassWorkflow,//TODO
            ByPass_RV__c = bypassValidationRules
        );
        
        Database.Saveresult sr = Database.insert(testUser,false);
        System.assert(sr.isSuccess(),'Utilisateur de Test pas créé');
        return testUser;
    }
    
    
}